### ISSUE TITLE
useQueryParams must be used within a QueryParamProvider

### ISSUE THREAD

**Issue by nwbhatia** [amannn/next-query-params#11]
Hi, I'm seeing the following error when trying to useQueryParams:

`Error: useQueryParams must be used within a QueryParamProvider`

Here's the relevant subset of my dependency versions:

```
    "@mui/material": "^5.4.4",
    "next": "12.1.0",
    "next-query-params": "^2.1.2",
    "prop-types": "^15.8.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "yarn": "^1.22.17"
```

My `_app.tsx` looks like this:

```
export default function MyApp(props: MyAppProps) {
  const { Component, emotionCache = clientSideEmotionCache, pageProps } = props;
  return (
    <NextQueryParamProvider>
      <CacheProvider value={emotionCache}>
        <Head>
          <meta name="viewport" content="initial-scale=1, width=device-width" />
        </Head>
        <ThemeProvider theme={theme}>
          {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
          <CssBaseline />
          <AuthProvider>
            <Component {...pageProps} />
          </AuthProvider>
        </ThemeProvider>
      </CacheProvider>
    </NextQueryParamProvider>
  );
}
```

In my `index.tsx` I have:

```
  const [selectedTags, setSelectedTags] = useQueryParams(
    Object.values(SearchTagCategory)
      .filter((key) => !isNaN(Number(key)))
      .reduce((res, tag) => {
        res[tag] = withDefault(ArrayParam, []);
        return res;
      }, {})
  );
```

I've tried moving the `<NextQueryParamProvider>` component around (deeper in the `_app.tsx` nesting, or even just wrapping my `index.tsx` component), but still can't fix this error. 

Please let me know if I'm missing something obvious! 😅

**Comment by balthazar** [comment]
Same issue, I'm guessing it's a problem with a new version of NextJS

**Comment by nwbhatia** [comment]
I unblocked using the latest manual implementation from the original issue thread: https://github.com/pbeshai/use-query-params/issues/13#issuecomment-815577849

**Comment by balthazar** [comment]
Haha did that at the same time 😄

**Comment by amannn** [comment]
Thanks for the report! I'm preparing a new version that is tested with the latest versions of Next.js and React in https://github.com/amannn/next-query-params/pull/12.

Would someone of you like to give it a go?

```
npm install next-query-params@3.0.0-alpha.1
```

Note that there's a breaking change in that IE11 is no longer supported (since React 18 also doesn't support it anymore).

**Comment by amannn** [comment]
@nwbhatia Did you have a chance to try the alpha out in your project?

**Comment by AugusDogus** [comment]
Hi all, I have been using `next-query-params@3.0.0-alpha.1` recently in a new project with Next.js 12.2 and I happy to report that I've noticed no issues so far.

**Comment by NiestrojMateusz** [comment]
Hi, what is the status of version 3? Any release plan of stable version?

**Comment by ryan-williams** [comment]
I started reading https://github.com/pbeshai/use-query-params/issues/13 comments from 2019, was amazed to see people's code there turn into this package, sad when I hit this issue, and then amazed again to see the story come right up to recent days/hours 😂

In any case, `next-query-params@3.0.0-alpha.1` works for me, thanks so much all! 🙏 never had a "google my error" journey quite like that before.
