### ISSUE TITLE
Next Query Params and enableBatching

### ISSUE THREAD

**Issue by JohannKaltner** [amannn/next-query-params#16]
Hey!

first I would like to congratulate you for the work that has been done with the library, it's amazing!

but I would like to report a problem, apparently it is not possible to update two params at the same time

for example:
setIsModal1Open(false)
setIsModal2Open(true)

I saw that use-query-params v2 has the `enableBatching` option. any ideas on when v2 will be implemented?

for reference: https://github.com/pbeshai/use-query-params/issues/53

**Comment by amannn** [comment]
Hi @JohannKaltner,

that's a good point you're raising! Would you be interested in contributing a pull request that updates the library to `use-query-params@2` and add a test for the `enableBatching` feature?

**Comment by amannn** [comment]
FYI I've got a new version in the works: https://github.com/amannn/next-query-params/pull/19

Feel free to give the pre-release a go if you like!
