### ISSUE TITLE
use-query-params dependency is out of date

### ISSUE THREAD

**Issue by mifrej** [amannn/next-query-params#18]
Any plans to update this middleware to utilize the new v2 version of [use-query-params](https://github.com/pbeshai/use-query-params)?

**Comment by amannn** [comment]
Hello @mifrej,

yep, this was raised previously in #16. I just found some time to prepare a release. Would you like to help out by trying the pre-release from https://github.com/amannn/next-query-params/pull/19 in your app to see if it works as expected for you?
