### ISSUE TITLE
Doesn't work with Next 13 yet

### ISSUE THREAD

**Issue by elie222** [amannn/next-query-params#22]
The fix might be to just update the deps to allow for Next 13 too:
https://github.com/amannn/next-query-params/blob/main/packages/next-query-params/package.json#L36

**Comment by amannn** [comment]
That's probably fine, yes! Would you be interested in contributing this change and updating the example (which is used for e2e tests) to Next.js 13?

**Comment by aaron5670** [comment]
Follow 👀

**Comment by elie222** [comment]
Sorry, haven't had time to get to it yet
