### ISSUE TITLE
Unable to disable scroll to top while changing query params

### ISSUE THREAD

**Issue by Electron-2002** [amannn/next-query-params#31]
Scroll to top is still happening when I am using next-query-params@4.2.1. Any solution for that?

I tried using this: https://github.com/pbeshai/use-query-params/issues/13#issuecomment-815577849, but it shows NextRouter was not mounted.

I think next-query-params is scrolling to top by default as { scroll: false} has not been used while doing router.push or router.replace.

**Comment by amannn** [comment]
That's an issue in Next.js as far as I know: https://github.com/vercel/next.js/issues/49087

**Comment by khanakia** [comment]
I was getting the error `NextRouter was not mounted` so i used this code https://github.com/pbeshai/use-query-params/issues/13#issuecomment-1553274435 it worked like a charm.

Can you update your library code according to that guy suggested ?
