### ISSUE TITLE
Version without compiled dependencies

### ISSUE THREAD

**Issue by elstgav** [amannn/next-query-params#4]
Thanks for creating this package! I was hoping to avoid copy-pasting the code from https://github.com/pbeshai/use-query-params/issues/13 —however our team doesn’t need IE11 support, so I’d like to avoid unnecessary code in our bundle.

Can you offer a version that doesn’t include `use-query-params` compiled inside the package? That would also enable us to update `use-query-params` independently of this package, for future maintenance.

**Comment by amannn** [comment]
Hi @elstgav,

thank you for your feedback. I agree, I also wouldn't want to bundle `use-query-params` if it's not necessary, but it's unfortunately required for IE11 support. If Next.js would compile `node_modules` similar to how CRA does, this wouldn't be necessary, so I think I'd wait for support from their side before changing this. Adding a separate entry point sounds like a potential footgun to me, as if you're not careful you could end up importing both versions.

Btw. the IE11 support is mostly about compiling arrow functions to function declarations, `const` to `var` etc. – so there shouldn't be a relevant overhead. Currently also the latest version of `use-query-params` is in use.

What do you think?

**Comment by elstgav** [comment]
Hi @amannn, thanks for the explanation! I hadn’t dug to see the extent of IE11 support but that definitely sounds like minimal overhead. I’m still not sure I fully understand why the compilation is necessary—if a client of `next-query-params` needs IE11 support couldn’t they version-lock `query-string` and others in their package.json file?

Either way, since it sounds like the overhead is minimal I think we can probably use this—thanks for putting this together in a package 🙏🏻

**Comment by amannn** [comment]
> if a client of next-query-params needs IE11 support couldn’t they version-lock query-string and others in their package.json file?

They could, but then they'd have to stick to an old version of `query-string` which is missing some bug fixes and features. I'd really like to make the consumption of this library as easy as possible and without having the consumer stuggle with compatibility issues. That's the reason why I went with the compilation approach for now.

We can leave this issue open as I definitely would like to move away from the compilation at some point, but I don't see a better alternative yet. Thanks for opening the discussion!

Btw. this topic is discussed over at Next.js: https://github.com/vercel/next.js/discussions/27876#discussioncomment-1188230

**Comment by fgblomqvist** [comment]
Nextjs 12 is now out, and they now officially support ESM afaik. Furthermore, why is IE11 support the default in 2021? I feel like it would make more sense for a small non-legacy library like this to not default to supporting the people that are still supporting IE11 😕. Having a second import as suggested earlier should be easy enough if you really still want to support a dead, insecure, unsupported browser.

**Comment by amannn** [comment]
> Nextjs 12 is now out, and they now officially support ESM afaik.

That's true, but it doesn't solve the problem with compiling e.g. arrow functions in `query-string` – right? See e.g. https://github.com/vercel/next.js/discussions/27876#discussioncomment-1188230.

> why is IE11 support the default in 2021?

Next.js also supports IE11. At least as long as they do, I think libraries for Next.js should aim for the same target.

Also I'm not sure what the problem is with supporting IE11? Dropping the support for that browser would have next to no effect on modern browsers. How much would you be able to reduce bundle size when `() => {}` is no longer converted to `function() {}`?

**Comment by fgblomqvist** [comment]
> That's true, but it doesn't solve the problem with compiling e.g. arrow functions in `query-string` – right? See e.g. [vercel/next.js#27876 (comment)](https://github.com/vercel/next.js/discussions/27876#discussioncomment-1188230).

Fair enough, but wouldn't people needing IE11 support just use something like https://github.com/martpie/next-transpile-modules anyway? What are the odds that the only library they use that doesn't support IE11 would be this?

> Also I'm not sure what the problem is with supporting IE11? Dropping the support for that browser would have next to no effect on modern browsers. How much would you be able to reduce bundle size when `() => {}` is no longer converted to `function() {}`?

I think @elstgav's argument about not bundling deps makes sense. It's just a weird thing to do in a package that's mean to be managed by a package manager imo. Are there cases where it doesn't make a difference? Most certainly. Does that make it universally the best option? I wouldn't say so.

**Comment by amannn** [comment]
I definitely agree that bundling dependencies isn't ideal – please don't get me wrong. 

But my commitment with the libraries I publish is to make it as easy as possible to consume them and without any strings attached. I tried to explain my position in the above comments. Ideally Next.js would handle this in a similar way as CRA does IMO.

**Comment by fgblomqvist** [comment]
You didn't address the point about `next-transpile-modules`. It literally changes Next.js to handle things like CRA does (i.e. to transpile all the node_modules). It's very popular and I am certain that people that are dealing with IE compatibility are already using it.

**Comment by amannn** [comment]
I think the big difference to CRA is that this not handled automatically in Next.js. I've seen so many issues of people complaining to library authors that their published code doesn't work in browser X. Every hoop the user has to jump through to use a library should be carefully justified and in this case I just don't see it, sorry.

But again: As soon as Next.js supports this the same way as CRA or Next.js drops IE11 support, I definitely want to change this.

**Comment by amannn** [comment]
Another update: [React 18 is dropping support for IE11](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#dropping-support-for-internet-explorer), so I think once that release is out we can remove the support for this browser as well.
