### ISSUE TITLE
Next.js 12 support

### ISSUE THREAD

**Issue by BrentChesny** [amannn/next-query-params#7]
The current version is not compatible with Next.js 12. I'm not sure if any specific changes need to happen for that, or that it just needs a change to the peer dependencies.

**Comment by amannn** [comment]
Thanks for the hint! Seems like it's just a matter of updating the `peerDependencies`, I'll have a release for this shortly …

**Comment by BrentChesny** [comment]
Awesome, thanks for the very quick response!
